import type { Metadata } from "next";
import "./globals.css";
import ProductNavbar from "@/components/ProductNavbar/page";

export const metadata: Metadata = {
  title: "Aloy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
        <ProductNavbar text="(ctrl +/)" />
        {children}
      </body>
    </html>
  );
}
