import type { Metadata } from "next";
import { Inter, Roboto, Raleway, Poppins, DM_Sans, Lora, Libre_Franklin } from "next/font/google";
import "./globals.css";
import ProductNavbar from "@/components/ProductNavbar/page";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ['400', '700', '500', '100', '300'] });
const raleway = Raleway({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ['400', '700', '500', '600'] });
const dm_sans = DM_Sans({ subsets: ["latin"], weight: ['400', '700', '500', '600'] });
const lora = Lora({ subsets: ["latin"], weight: ['400', '700', '500', '600'] });
const libre_franklin = Libre_Franklin({ subsets: ["latin"], weight: ['400', '700', '500', '600'] });

export const metadata: Metadata = {
  title: "Aloy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
        <ProductNavbar text="(ctrl +/)" />
        {children}
      </body>
    </html>
  );
}
